version: '3.8'
services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"